In [ ]:
import pandas as pd
data = { 
    "Name" : ["Anish","Sachin","Kartik","Soham","Om","Amit","Raj","Hitesh","Ram"],
    "Age" :[17,18,19,16,15,19,23,22,23],
    "City" :["Nashik","Pune","Mumbai","Dubai","Nashik","Deola","New York","Brazil","Africa"],
    "Marks":[90,20,45,79,89,23,45,67,99]}
df = pd.DataFrame(data)
print(df)

     Name  Age      City  Marks
0   Suraj   17    Nashik     90
1   Shree   18      Pune     20
2   Krish   19    Mumbai     45
3  Saquib   16     Dubai     79
4      Om   15    Nashik     89
5   Mohit   19     Deola     23
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99

In [2]:
df.head()

     Name  Age    City  Marks
0   Suraj   17  Nashik     90
1   Shree   18    Pune     20
2   Krish   19  Mumbai     45
3  Saquib   16   Dubai     79
4      Om   15  Nashik     89

In [3]:
df.tail()

     Name  Age      City  Marks
4      Om   15    Nashik     89
5   Mohit   19     Deola     23
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99

In [4]:
df.shape

(9, 4)

In [5]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      str
 1   Age     9 non-null      int64
 2   City    9 non-null      str
 3   Marks   9 non-null      int64
dtypes: int64(2), str(2)
memory usage: 420.0 bytes

In [8]:
df.describe()

             Age      Marks
count   9.000000   9.000000
mean   19.111111  61.888889
std     2.976762  29.704564
min    15.000000  20.000000
25%    17.000000  45.000000
50%    19.000000  67.000000
75%    22.000000  89.000000
max    23.000000  99.000000

In [10]:
df.to_csv("Students.csv",index = False)

In [11]:
students=pd.read_csv("Students.csv")

In [12]:
print(students)

     Name  Age      City  Marks
0   Suraj   17    Nashik     90
1   Shree   18      Pune     20
2   Krish   19    Mumbai     45
3  Saquib   16     Dubai     79
4      Om   15    Nashik     89
5   Mohit   19     Deola     23
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99

In [13]:
df[["Name"]]

     Name
0   Suraj
1   Shree
2   Krish
3  Saquib
4      Om
5   Mohit
6     Raj
7  Hitesh
8     Ram

In [14]:
df[df["Age"]>18]

     Name  Age      City  Marks
2   Krish   19    Mumbai     45
5   Mohit   19     Deola     23
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99

In [19]:
df[df["City"]== "Mumbai"]

    Name  Age    City  Marks
2  Krish   19  Mumbai     45

In [22]:
df[df["Marks"].between(50,100)]

     Name  Age    City  Marks
0   Suraj   17  Nashik     90
3  Saquib   16   Dubai     79
4      Om   15  Nashik     89
7  Hitesh   22  Brazil     67
8     Ram   23  Africa     99

In [28]:
print(df[(df["City"]== "Mumbai") & (df["Marks"]>=45)])

    Name  Age    City  Marks
2  Krish   19  Mumbai     45

In [31]:
print(df.sort_values(by="Marks"))

     Name  Age      City  Marks
1   Shree   18      Pune     20
5   Mohit   19     Deola     23
6     Raj   23  New York     45
2   Krish   19    Mumbai     45
7  Hitesh   22    Brazil     67
3  Saquib   16     Dubai     79
4      Om   15    Nashik     89
0   Suraj   17    Nashik     90
8     Ram   23    Africa     99

In [32]:
print(df.sort_values(by="Marks", ascending=False))

     Name  Age      City  Marks
8     Ram   23    Africa     99
0   Suraj   17    Nashik     90
4      Om   15    Nashik     89
3  Saquib   16     Dubai     79
7  Hitesh   22    Brazil     67
6     Raj   23  New York     45
2   Krish   19    Mumbai     45
5   Mohit   19     Deola     23
1   Shree   18      Pune     20

In [33]:
print(df["City"].unique())

<StringArray>
['Nashik', 'Pune', 'Mumbai', 'Dubai', 'Deola', 'New York', 'Brazil', 'Africa']
Length: 8, dtype: str

In [35]:
print(df["City"].value_counts())

City
Nashik      2
Pune        1
Mumbai      1
Dubai       1
Deola       1
New York    1
Brazil      1
Africa      1
Name: count, dtype: int64

In [36]:
print(df[df.duplicated()])

Empty DataFrame
Columns: [Name, Age, City, Marks]
Index: []

In [37]:
df.drop_duplicates()

     Name  Age      City  Marks
0   Suraj   17    Nashik     90
1   Shree   18      Pune     20
2   Krish   19    Mumbai     45
3  Saquib   16     Dubai     79
4      Om   15    Nashik     89
5   Mohit   19     Deola     23
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99

In [39]:
print(df.isnull())

    Name    Age   City  Marks
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False

In [40]:
print(df.isnull().sum())

Name     0
Age      0
City     0
Marks    0
dtype: int64

In [41]:
print(df)

     Name  Age      City  Marks
0   Suraj   17    Nashik     90
1   Shree   18      Pune     20
2   Krish   19    Mumbai     45
3  Saquib   16     Dubai     79
4      Om   15    Nashik     89
5   Mohit   19     Deola     23
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99