In [ ]:
import pandas as pd
data = { 
    "Name" : ["Anish","Soham","Kartik","Sachin","Om","Rohit","Ajay","rohan","Roshan"],
    "Age" :[17,18,19,16,15,19,23,22,23],
    "City" :["Nashik","Pune","Mumbai","Dubai","Nashik","Deola","New York","France","Africa"],
    "Marks":[90,20,45,79,89,23,45,67,99]}
df = pd.DataFrame(data)
df.head()
df.head(2)

    Name  Age    City  Marks
0  Suraj   17  Nashik     90
1  Shree   18    Pune     20

In [5]:
df.tail()
df.tail(3)

     Name  Age      City  Marks
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99

In [6]:
df.shape

(9, 4)

In [8]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='str')

In [10]:
df[df["Age"]>18]

     Name  Age      City  Marks
2   Krish   19    Mumbai     45
5   Mohit   19     Deola     23
6     Raj   23  New York     45
7  Hitesh   22    Brazil     67
8     Ram   23    Africa     99

In [12]:
df[df["City"]=="Nashik"]

    Name  Age    City  Marks
0  Suraj   17  Nashik     90
4     Om   15  Nashik     89

In [13]:
df[df["Marks"]>75]

     Name  Age    City  Marks
0   Suraj   17  Nashik     90
3  Saquib   16   Dubai     79
4      Om   15  Nashik     89
8     Ram   23  Africa     99

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      str
 1   Age     9 non-null      int64
 2   City    9 non-null      str
 3   Marks   9 non-null      int64
dtypes: int64(2), str(2)
memory usage: 420.0 bytes

In [15]:
df.describe()

             Age      Marks
count   9.000000   9.000000
mean   19.111111  61.888889
std     2.976762  29.704564
min    15.000000  20.000000
25%    17.000000  45.000000
50%    19.000000  67.000000
75%    22.000000  89.000000
max    23.000000  99.000000

In [25]:
df[(df["Marks"] > 75) & (df["City"] == "Nashik")]

    Name  Age    City  Marks
0  Suraj   17  Nashik     90
4     Om   15  Nashik     89

In [27]:
df[(df["City"]=="Pune") | (df["Marks"]>75)]

     Name  Age    City  Marks
0   Suraj   17  Nashik     90
1   Shree   18    Pune     20
3  Saquib   16   Dubai     79
4      Om   15  Nashik     89
8     Ram   23  Africa     99