In [ ]:
import pandas as pd

data = { 
    "Name" : ["Anish","Sachin","Kartik","Soham","Omesh","Mohan","Rohit","Harish","karan","Rohan"],
    "RollNo" :[17,18,19,25,20,16,21,22,23,24],
    "Department" :["AIML","CS","IT","ECE","Civil","AIML","ENTC","IT","CS","CS"],
    "Salary":[56000,23000,44000,78000,35000,22000,42000,34000,46000,14000]
}
df = pd.DataFrame(data)

In [34]:
df.sort_values(by="Salary")

     Name  RollNo Department  Salary
9     Ram      24         CS   12000
1   Shree      18         CS   20000
5   Mohit      16       AIML   23000
4      Om      20      Civil   34000
7  Hitesh      22         IT   34000
2   Krish      19         IT   45000
8   karan      23         CS   45000
6     Raj      21       ENTC   45000
0   Suraj      17       AIML   55000
3  Saquib      25        ECE   79000

In [35]:
#descending order
df.sort_values(by="Salary", ascending=False)

     Name  RollNo Department  Salary
3  Saquib      25        ECE   79000
0   Suraj      17       AIML   55000
8   karan      23         CS   45000
2   Krish      19         IT   45000
6     Raj      21       ENTC   45000
7  Hitesh      22         IT   34000
4      Om      20      Civil   34000
5   Mohit      16       AIML   23000
1   Shree      18         CS   20000
9     Ram      24         CS   12000

In [36]:
df["Department"].unique()

<StringArray>
['AIML', 'CS', 'IT', 'ECE', 'Civil', 'ENTC']
Length: 6, dtype: str

In [37]:
#employess from each Dept
df["Department"].value_counts()

Department
CS       3
AIML     2
IT       2
ECE      1
Civil    1
ENTC     1
Name: count, dtype: int64

In [38]:
df.groupby("Department")["Salary"].max()

Department
AIML     55000
CS       45000
Civil    34000
ECE      79000
ENTC     45000
IT       45000
Name: Salary, dtype: int64

In [39]:
df.groupby("Department")["Salary"].min()

Department
AIML     23000
CS       12000
Civil    34000
ECE      79000
ENTC     45000
IT       34000
Name: Salary, dtype: int64

In [40]:
df.sort_values(by="Department")

     Name  RollNo Department  Salary
0   Suraj      17       AIML   55000
5   Mohit      16       AIML   23000
1   Shree      18         CS   20000
8   karan      23         CS   45000
9     Ram      24         CS   12000
4      Om      20      Civil   34000
3  Saquib      25        ECE   79000
6     Raj      21       ENTC   45000
2   Krish      19         IT   45000
7  Hitesh      22         IT   34000

In [ ]:
'''
Questions and answers

Q1. Purpose of sort_values()?
It is used to sort data in ascending or descending order based on column values.

Q2. Difference between ascending and descending sorting?
Ascending sorting starts from small to large and descending sorting starts from large to small

Q3. Purpose of unique()?
It returns all unique (distinct) values from a column.

Q4. Purpose of value_counts()?
it returns count of each unique value in a column.

Q5. What is groupby()?
it is used to group records based on column name

Q6. Aggregation functions in Pandas
sum() → total
mean() → average
max() → highest value
min() → lowest value
count() → number of records 
'''