In [ ]:
import pandas as pd

data = { 
    "Name" : ["Anish","Sachin","Sneha","Aisha","Omesh","Poonam","Rohit","Harish","karan","Rohan"],
    "RollNo" :[11,18,19,25,20,16,21,22,23,24],
    "Department" :["AIML","CS","IT","ECE","Civil","AIML","ENTC","IT","CS","CS"],
    "Salary":[55000,20000,45000,79000,34000,23000,45000,35000,44000,14000],
    "Gender":["Male","Male","Female","Female","Male","Female","Male","Male","Male","Male"],
    "Status":["Not_Purchased","Purchased","Not_Purchased","Purchased","Not_Purchased","Purchased","Not_Purchased","Not_Purchased","Not_Purchased","Purchased",]
}
df = pd.DataFrame(data)

In [17]:
df.head()

      Name  RollNo Department  Salary  Gender         Status
0    Suraj      17       AIML   55000    Male  Not_Purchased
1    Shree      18         CS   20000    Male      Purchased
2   Snehal      19         IT   45000  Female  Not_Purchased
3  Akansha      25        ECE   79000  Female      Purchased
4       Om      20      Civil   34000    Male  Not_Purchased

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     str
 1   RollNo      10 non-null     int64
 2   Department  10 non-null     str
 3   Salary      10 non-null     int64
 4   Gender      10 non-null     str
 5   Status      10 non-null     str
dtypes: int64(2), str(4)
memory usage: 612.0 bytes

In [19]:
df.describe()

         RollNo        Salary
count  10.00000     10.000000
mean   20.50000  39200.000000
std     3.02765  19320.685518
min    16.00000  12000.000000
25%    18.25000  25750.000000
50%    20.50000  39500.000000
75%    22.75000  45000.000000
max    25.00000  79000.000000

In [21]:
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})
df["Status"]=df["Status"].map({"Purchased":0,"Not_Purchased":1})

In [22]:
print(df)

      Name  RollNo Department  Salary  Gender  Status
0    Suraj      17       AIML   55000     NaN       1
1    Shree      18         CS   20000     NaN       0
2   Snehal      19         IT   45000     NaN       1
3  Akansha      25        ECE   79000     NaN       0
4       Om      20      Civil   34000     NaN       1
5    Payal      16       AIML   23000     NaN       0
6      Raj      21       ENTC   45000     NaN       1
7   Hitesh      22         IT   34000     NaN       1
8    karan      23         CS   45000     NaN       1
9      Ram      24         CS   12000     NaN       0

In [23]:
df[["RollNo","Salary"]].corr()

          RollNo    Salary
RollNo  1.000000  0.290617
Salary  0.290617  1.000000

In [25]:
X = df[["RollNo", "Salary", "Gender"]]

In [26]:
Y = df["Status"]

In [27]:
print(X)

   RollNo  Salary  Gender
0      17   55000     NaN
1      18   20000     NaN
2      19   45000     NaN
3      25   79000     NaN
4      20   34000     NaN
5      16   23000     NaN
6      21   45000     NaN
7      22   34000     NaN
8      23   45000     NaN
9      24   12000     NaN

In [28]:
print(Y)

0    1
1    0
2    1
3    0
4    1
5    0
6    1
7    1
8    1
9    0
Name: Status, dtype: int64

In [ ]:
'''
Questions and answers 
Q1. What is Data Exploration?

Data Exploration is the process of analyzing data to understand its structure, patterns, and summary statistics.

Q2. What is a Feature in Machine Learning?

A Feature is an input variable used to train a machine learning model.

Q3. What is a Target Variable?

A Target Variable is the output we want to predict in machine learning.

Q4. What is Correlation?

Correlation measures the relationship between two variables (ranges from -1 to +1).

Q5. Why is Encoding required in Machine Learning?

Encoding is required to convert categorical data into numerical form so that ML models can understand it.

Q6. Difference between Training Data and Testing Data?

Training data is used to train the model, while testing data is used to evaluate its performance.
'''